// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: statestore/statestore.proto

package statestore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	State         *structpb.Struct       `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // flexible JSON-like blob, maps to your JSONB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_statestore_statestore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statestore_statestore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_statestore_statestore_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateSessionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateSessionRequest) GetState() *structpb.Struct {
	if x != nil {
		return x.State
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // still required — enforcing tenant scoping at the API level too
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_statestore_statestore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statestore_statestore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_statestore_statestore_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSessionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListSessionsByTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsByTenantRequest) Reset() {
	*x = ListSessionsByTenantRequest{}
	mi := &file_statestore_statestore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsByTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsByTenantRequest) ProtoMessage() {}

func (x *ListSessionsByTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statestore_statestore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsByTenantRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsByTenantRequest) Descriptor() ([]byte, []int) {
	return file_statestore_statestore_proto_rawDescGZIP(), []int{2}
}

func (x *ListSessionsByTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	State         *structpb.Struct       `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_statestore_statestore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_statestore_statestore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_statestore_statestore_proto_rawDescGZIP(), []int{3}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Session) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Session) GetState() *structpb.Struct {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_statestore_statestore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statestore_statestore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_statestore_statestore_proto_rawDescGZIP(), []int{4}
}

func (x *SessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"` // "repeated" = a list/array in protobuf
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_statestore_statestore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statestore_statestore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_statestore_statestore_proto_rawDescGZIP(), []int{5}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

var File_statestore_statestore_proto protoreflect.FileDescriptor

const file_statestore_statestore_proto_rawDesc = "" +
	"\n" +
	"\x1bstatestore/statestore.proto\x12\n" +
	"statestore\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"}\n" +
	"\x14CreateSessionRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12-\n" +
	"\x05state\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05state\"@\n" +
	"\x11GetSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\":\n" +
	"\x1bListSessionsByTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\xf6\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12-\n" +
	"\x05state\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x05state\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"@\n" +
	"\x0fSessionResponse\x12-\n" +
	"\asession\x18\x01 \x01(\v2\x13.statestore.SessionR\asession\"G\n" +
	"\x14ListSessionsResponse\x12/\n" +
	"\bsessions\x18\x01 \x03(\v2\x13.statestore.SessionR\bsessions2\x90\x02\n" +
	"\x11StateStoreService\x12N\n" +
	"\rCreateSession\x12 .statestore.CreateSessionRequest\x1a\x1b.statestore.SessionResponse\x12H\n" +
	"\n" +
	"GetSession\x12\x1d.statestore.GetSessionRequest\x1a\x1b.statestore.SessionResponse\x12a\n" +
	"\x14ListSessionsByTenant\x12'.statestore.ListSessionsByTenantRequest\x1a .statestore.ListSessionsResponseB5Z3github.com/Henildiyora/nexus/internal/pb/statestoreb\x06proto3"

var (
	file_statestore_statestore_proto_rawDescOnce sync.Once
	file_statestore_statestore_proto_rawDescData []byte
)

func file_statestore_statestore_proto_rawDescGZIP() []byte {
	file_statestore_statestore_proto_rawDescOnce.Do(func() {
		file_statestore_statestore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_statestore_statestore_proto_rawDesc), len(file_statestore_statestore_proto_rawDesc)))
	})
	return file_statestore_statestore_proto_rawDescData
}

var file_statestore_statestore_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_statestore_statestore_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),        // 0: statestore.CreateSessionRequest
	(*GetSessionRequest)(nil),           // 1: statestore.GetSessionRequest
	(*ListSessionsByTenantRequest)(nil), // 2: statestore.ListSessionsByTenantRequest
	(*Session)(nil),                     // 3: statestore.Session
	(*SessionResponse)(nil),             // 4: statestore.SessionResponse
	(*ListSessionsResponse)(nil),        // 5: statestore.ListSessionsResponse
	(*structpb.Struct)(nil),             // 6: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),       // 7: google.protobuf.Timestamp
}
var file_statestore_statestore_proto_depIdxs = []int32{
	6, // 0: statestore.CreateSessionRequest.state:type_name -> google.protobuf.Struct
	6, // 1: statestore.Session.state:type_name -> google.protobuf.Struct
	7, // 2: statestore.Session.created_at:type_name -> google.protobuf.Timestamp
	7, // 3: statestore.Session.updated_at:type_name -> google.protobuf.Timestamp
	3, // 4: statestore.SessionResponse.session:type_name -> statestore.Session
	3, // 5: statestore.ListSessionsResponse.sessions:type_name -> statestore.Session
	0, // 6: statestore.StateStoreService.CreateSession:input_type -> statestore.CreateSessionRequest
	1, // 7: statestore.StateStoreService.GetSession:input_type -> statestore.GetSessionRequest
	2, // 8: statestore.StateStoreService.ListSessionsByTenant:input_type -> statestore.ListSessionsByTenantRequest
	4, // 9: statestore.StateStoreService.CreateSession:output_type -> statestore.SessionResponse
	4, // 10: statestore.StateStoreService.GetSession:output_type -> statestore.SessionResponse
	5, // 11: statestore.StateStoreService.ListSessionsByTenant:output_type -> statestore.ListSessionsResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_statestore_statestore_proto_init() }
func file_statestore_statestore_proto_init() {
	if File_statestore_statestore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_statestore_statestore_proto_rawDesc), len(file_statestore_statestore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_statestore_statestore_proto_goTypes,
		DependencyIndexes: file_statestore_statestore_proto_depIdxs,
		MessageInfos:      file_statestore_statestore_proto_msgTypes,
	}.Build()
	File_statestore_statestore_proto = out.File
	file_statestore_statestore_proto_goTypes = nil
	file_statestore_statestore_proto_depIdxs = nil
}
