// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: statestore/statestore.proto

package statestore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StateStoreService_CreateSession_FullMethodName        = "/statestore.StateStoreService/CreateSession"
	StateStoreService_GetSession_FullMethodName           = "/statestore.StateStoreService/GetSession"
	StateStoreService_ListSessionsByTenant_FullMethodName = "/statestore.StateStoreService/ListSessionsByTenant"
	StateStoreService_UpdateSession_FullMethodName        = "/statestore.StateStoreService/UpdateSession"
	StateStoreService_DeleteSession_FullMethodName        = "/statestore.StateStoreService/DeleteSession"
	StateStoreService_GetSessionAsOf_FullMethodName       = "/statestore.StateStoreService/GetSessionAsOf"
)

// StateStoreServiceClient is the client API for StateStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The service definition — this becomes an interface you implement in Go,
// and a client stub you can call from Go, Python, etc.
type StateStoreServiceClient interface {
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	ListSessionsByTenant(ctx context.Context, in *ListSessionsByTenantRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	GetSessionAsOf(ctx context.Context, in *GetSessionAsOfRequest, opts ...grpc.CallOption) (*SessionResponse, error)
}

type stateStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStateStoreServiceClient(cc grpc.ClientConnInterface) StateStoreServiceClient {
	return &stateStoreServiceClient{cc}
}

func (c *stateStoreServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, StateStoreService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, StateStoreService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) ListSessionsByTenant(ctx context.Context, in *ListSessionsByTenantRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, StateStoreService_ListSessionsByTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, StateStoreService_UpdateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, StateStoreService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateStoreServiceClient) GetSessionAsOf(ctx context.Context, in *GetSessionAsOfRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, StateStoreService_GetSessionAsOf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateStoreServiceServer is the server API for StateStoreService service.
// All implementations must embed UnimplementedStateStoreServiceServer
// for forward compatibility.
//
// The service definition — this becomes an interface you implement in Go,
// and a client stub you can call from Go, Python, etc.
type StateStoreServiceServer interface {
	CreateSession(context.Context, *CreateSessionRequest) (*SessionResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*SessionResponse, error)
	ListSessionsByTenant(context.Context, *ListSessionsByTenantRequest) (*ListSessionsResponse, error)
	UpdateSession(context.Context, *UpdateSessionRequest) (*SessionResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	GetSessionAsOf(context.Context, *GetSessionAsOfRequest) (*SessionResponse, error)
	mustEmbedUnimplementedStateStoreServiceServer()
}

// UnimplementedStateStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStateStoreServiceServer struct{}

func (UnimplementedStateStoreServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*SessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedStateStoreServiceServer) GetSession(context.Context, *GetSessionRequest) (*SessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedStateStoreServiceServer) ListSessionsByTenant(context.Context, *ListSessionsByTenantRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessionsByTenant not implemented")
}
func (UnimplementedStateStoreServiceServer) UpdateSession(context.Context, *UpdateSessionRequest) (*SessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSession not implemented")
}
func (UnimplementedStateStoreServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedStateStoreServiceServer) GetSessionAsOf(context.Context, *GetSessionAsOfRequest) (*SessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionAsOf not implemented")
}
func (UnimplementedStateStoreServiceServer) mustEmbedUnimplementedStateStoreServiceServer() {}
func (UnimplementedStateStoreServiceServer) testEmbeddedByValue()                           {}

// UnsafeStateStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StateStoreServiceServer will
// result in compilation errors.
type UnsafeStateStoreServiceServer interface {
	mustEmbedUnimplementedStateStoreServiceServer()
}

func RegisterStateStoreServiceServer(s grpc.ServiceRegistrar, srv StateStoreServiceServer) {
	// If the following call panics, it indicates UnimplementedStateStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StateStoreService_ServiceDesc, srv)
}

func _StateStoreService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_ListSessionsByTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsByTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).ListSessionsByTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_ListSessionsByTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).ListSessionsByTenant(ctx, req.(*ListSessionsByTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_UpdateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).UpdateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_UpdateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).UpdateSession(ctx, req.(*UpdateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateStoreService_GetSessionAsOf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionAsOfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateStoreServiceServer).GetSessionAsOf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StateStoreService_GetSessionAsOf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateStoreServiceServer).GetSessionAsOf(ctx, req.(*GetSessionAsOfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StateStoreService_ServiceDesc is the grpc.ServiceDesc for StateStoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StateStoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "statestore.StateStoreService",
	HandlerType: (*StateStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _StateStoreService_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _StateStoreService_GetSession_Handler,
		},
		{
			MethodName: "ListSessionsByTenant",
			Handler:    _StateStoreService_ListSessionsByTenant_Handler,
		},
		{
			MethodName: "UpdateSession",
			Handler:    _StateStoreService_UpdateSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _StateStoreService_DeleteSession_Handler,
		},
		{
			MethodName: "GetSessionAsOf",
			Handler:    _StateStoreService_GetSessionAsOf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "statestore/statestore.proto",
}
